# 应用配置
server:
  port: 8099
## es数据源配置
elasticsearch:
  host: localhost
  clustername: elasticsearch
  port: 9300

# mybatis配置
mybatis:
  type-aliases-package: com.example.esdemo.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webhook?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver